"""A hermetic kernel cc toolchain over an LLVM distribution Bazel fetched
(toolchains_llvm's `@llvm_toolchain_llvm`): a repository whose `bin/` links
the distribution's tools, so the toolchain can name them by *package-relative*
`tool_paths` (docs/FRONTEND-kbuild.md).

Why a repository: rules_cc resolves `tool_paths` relative to the cc_toolchain's
package and rejects `..` segments, so a toolchain in the main repository cannot
point its `nm`/`ld`/`objcopy` at files of another repository -- and the make
variables genrules get ($(NM), $(LD), $(OBJCOPY), $(STRIP), $(AR)) come from
`tool_paths` only (there is no action to fall back on for nm). The label route
of kernel_cc_toolchain_config (action_configs) drives compiles and archives
fine but leaves those variables empty. This repository is the toolchains_llvm
pattern: links in `bin/`, `tool_prefix = "bin/"`.

    # MODULE.bazel
    kernel_llvm_toolchain = use_repo_rule("//bazel/rules:kernel_llvm_toolchain.bzl",
                                          "kernel_llvm_toolchain")
    kernel_llvm_toolchain(
        name = "kernel_llvm",
        clang = "@llvm_toolchain_llvm//:bin/clang",
        files = ["@llvm_toolchain_llvm//:bin", "@llvm_toolchain_llvm//:lib",
                 "@llvm_toolchain_llvm//:include"],
        config_bzl = "//bazel/rules:kernel_cc_toolchain_config.bzl",
        flags_bzl = "//toolchain:kernel_flags.bzl",      # KERNEL_COPTS, KERNEL_INCLUDE_DIRS
        include_roots_symbol = "KERNEL_INCLUDE_ROOTS",   # the feature's -I line
        target_cpu = "x86_64",
        target_system_name = "x86_64-linux-gnu",
        target_compatible_with = ["@platforms//os:linux", "@platforms//cpu:x86_64",
                                  "//platforms:kernel"],
    )
    register_toolchains("@kernel_llvm//:toolchain")
"""

_DEFAULT_TOOLS = {
    "gcc": "clang",
    "g++": "clang++",
    "cpp": "clang-cpp",
    "ld": "ld.lld",
    "ar": "llvm-ar",
    "nm": "llvm-nm",
    "objcopy": "llvm-objcopy",
    "objdump": "llvm-objdump",
    "strip": "llvm-strip",
    "gcov": "llvm-cov",
}

_BUILD = '''# Generated by kernel_llvm_toolchain (any2bazel bazel/rules): the kernel cc
# toolchain over the LLVM distribution at {llvm_bin}, its tools linked in bin/.
load("@rules_cc//cc:defs.bzl", "cc_toolchain")
load("{config_bzl}", "kernel_cc_toolchain_config")
load("{flags_bzl}", {flag_symbols})

package(default_visibility = ["//visibility:public"])

exports_files(glob(["bin/*"]))

filegroup(name = "empty")

filegroup(
    name = "bin",
    srcs = glob(["bin/*"]),
)

filegroup(
    name = "all_files",
    srcs = [":bin"] + {files},
)

kernel_cc_toolchain_config(
    name = "config",
    tool_prefix = "bin/",
    tools = {tools},
    copts = {copts},
    include_dirs = {include_roots},
    builtin_include_directories = {include_dirs} + {builtin_include_directories},
    env = {env},
    target_cpu = "{target_cpu}",
    target_system_name = "{target_system_name}",
    toolchain_identifier = "{name}",
)

cc_toolchain(
    name = "cc_toolchain",
    all_files = ":all_files",
    ar_files = ":all_files",
    compiler_files = ":all_files",
    dwp_files = ":empty",
    linker_files = ":all_files",
    objcopy_files = ":all_files",
    strip_files = ":all_files",
    supports_param_files = 1,
    toolchain_config = ":config",
    toolchain_identifier = "{name}",
)

toolchain(
    name = "toolchain",
    exec_compatible_with = {exec_compatible_with},
    target_compatible_with = {target_compatible_with},
    toolchain = ":cc_toolchain",
    toolchain_type = "@rules_cc//cc:toolchain_type",
)
'''

def _labels(labels):
    return "[" + ", ".join(['"%s"' % str(l) for l in labels]) + "]"

def _impl(rctx):
    llvm_bin = rctx.path(rctx.attr.clang).dirname
    tools = dict(_DEFAULT_TOOLS)
    tools.update(rctx.attr.tools)
    names = {}
    for n in list(tools.values()) + rctx.attr.link:
        names[n] = True
    for n in names:
        src = llvm_bin.get_child(n)
        if src.exists:
            rctx.symlink(src, "bin/" + n)
    # The compiler reports the headers of its resource dir by the resource
    # dir's *real* path -- inside the fetched distribution's repository,
    # absolute in the build's cache. The depfile check ("absolute path
    # inclusion(s) found in rule") accepts an inclusion only if the toolchain
    # declares the directory it comes from, so declare the resource dirs the
    # linked compiler actually reads, by that real path. (The kernel's own
    # TUs are -nostdinc and never open them; it is the host-support code
    # compiled without -nostdinc -- the objtool support library -- that
    # does. The kernel_flags.bzl list plus these cover everything the
    # toolchain reads.)
    toolchain_builtins = []
    lib_clang = llvm_bin.dirname.get_child("lib").get_child("clang")
    if lib_clang.exists:
        real = rctx.execute(["/usr/bin/realpath", str(lib_clang)])
        if real.return_code == 0:
            base = real.stdout.strip()
            for v in lib_clang.readdir():
                for sub in ("include", "share"):
                    if v.get_child(sub).exists:
                        toolchain_builtins.append(base + "/" + v.basename + "/" + sub)
    include_roots = rctx.attr.include_roots_symbol or "[]"
    flag_symbols = ['"%s"' % rctx.attr.copts_symbol] \
        + ([] if include_roots == "[]" else ['"%s"' % include_roots])
    include_dirs = rctx.attr.include_dirs_symbol or "[]"
    rctx.file("BUILD.bazel", _BUILD.format(
        builtin_include_directories = repr(list(rctx.attr.builtin_include_directories) + toolchain_builtins),
        name = rctx.name,
        llvm_bin = str(llvm_bin),
        config_bzl = str(rctx.attr.config_bzl),
        flags_bzl = str(rctx.attr.flags_bzl),
        flag_symbols = ", ".join(flag_symbols),
        files = _labels(rctx.attr.files),
        tools = repr({k: v for k, v in tools.items() if llvm_bin.get_child(v).exists}),
        copts = rctx.attr.copts_symbol,
        include_roots = include_roots,
        include_dirs = include_dirs,
        env = repr(dict(rctx.attr.env)),
        target_cpu = rctx.attr.target_cpu,
        target_system_name = rctx.attr.target_system_name,
        exec_compatible_with = _labels(rctx.attr.exec_compatible_with),
        target_compatible_with = _labels(rctx.attr.target_compatible_with),
    ))

kernel_llvm_toolchain = repository_rule(
    implementation = _impl,
    attrs = {
        "clang": attr.label(mandatory = True, allow_single_file = True,
                            doc = "the distribution's compiler; its directory is the bin/ that is linked"),
        "files": attr.label_list(doc = "the distribution's files every action needs (bin, lib, include filegroups)"),
        "config_bzl": attr.label(mandatory = True, doc = "kernel_cc_toolchain_config.bzl"),
        "flags_bzl": attr.label(mandatory = True, doc = "the .bzl probe_kernel.py --common wrote"),
        "copts_symbol": attr.string(default = "KERNEL_COPTS"),
        "include_roots_symbol": attr.string(doc = "the kernel_flags.bzl symbol of the -I roots the toolchain's feature spells (KERNEL_INCLUDE_ROOTS); empty for none"),
        "include_dirs_symbol": attr.string(default = "KERNEL_INCLUDE_DIRS",
                                           doc = "its builtin include directories symbol; empty for none"),
        "builtin_include_directories": attr.string_list(
            doc = "further cxx_builtin_include_directories of the toolchain, beyond the kernel_flags.bzl "
                + "symbol's list: the directories compiles that read headers outside the kernel's own "
                + "(`-nostdinc` system dirs of the toolchain's `%workspace%`-relative resources and "
                + "the host's `/usr/include`, as toolchains_llvm spells them) may reach"),
        "tools": attr.string_dict(doc = "tool_paths name -> file in bin/, over the clang defaults (gcc: clang, ld: ld.lld, nm: llvm-nm, ...)"),
        "link": attr.string_list(doc = "further bin/ files to link (recipes naming them: llvm-readelf, ...)"),
        "env": attr.string_dict(),
        "target_cpu": attr.string(mandatory = True),
        "target_system_name": attr.string(mandatory = True),
        "exec_compatible_with": attr.label_list(default = ["@platforms//os:linux", "@platforms//cpu:x86_64"]),
        "target_compatible_with": attr.label_list(mandatory = True),
    },
    doc = "A kernel cc toolchain repository over a fetched LLVM distribution (see the module docstring).",
)
